-- Seed final system SOPs (41-59)
INSERT INTO public.sops (source, system_key, title, content_md, ack_required)
VALUES
  ('system', 'SOP-041', 'SOP-041 – Electrical Safety', E'PURPOSE\nTo prevent electrical injuries and equipment damage.\n\nRULES\n• Inspect cords daily.\n• Do not use damaged cords or tools.\n• Keep cords away from water.\n• Use GFCI protection where required.\n\nPROHIBITED\n• Overloading outlets.\n• Using makeshift repairs.\n• Running cords through water.', true),
  ('system', 'SOP-042', 'SOP-042 – Annual Training & Certification', E'PURPOSE\nTo ensure ongoing compliance and skill development.\n\nREQUIREMENTS\n• Annual review of SOPs.\n• Annual safety training.\n• Tool and equipment refresher training.\n• Documentation of completed training.\n\nFailure to complete training may result in discipline.', true),
  ('system', 'SOP-043', 'SOP-043 – Lead Paint Awareness', E'PURPOSE\nTo protect workers and occupants from lead exposure.\n\nRULES\n• Assume pre-1990 buildings may contain lead paint.\n• Do not disturb suspected lead paint without approval.\n• No dry sanding of suspect materials.\n• Use containment and dust control.\n\nIF LEAD IS SUSPECTED\n• Stop work immediately.\n• Notify foreman and management.\n• Do not resume until cleared.', true),
  ('system', 'SOP-044', 'SOP-044 – Respirator Use & Care', E'PURPOSE\nTo ensure respirators are used correctly.\n\nRULES\n• Use respirators when required by task or SDS.\n• Employees must be fit-tested.\n• Facial hair that interferes with seal is prohibited.\n\nCARE\n• Clean respirators after each use.\n• Store in sealed, clean containers.\n• Inspect before each use.', true),
  ('system', 'SOP-045', 'SOP-045 – Personal Protective Equipment (PPE)', E'PURPOSE\nTo establish minimum PPE standards.\n\nREQUIRED PPE\n• Safety glasses, gloves, respirators\n• Hearing protection, protective clothing\n\nRULES\n• PPE must be worn when required.\n• PPE must be clean and in good condition.\n• Do not modify PPE.\n\nFailure to wear PPE is a safety violation.', true),
  ('system', 'SOP-046', 'SOP-046 – Jobsite Signage & Barricading', E'PURPOSE\nTo protect workers, customers, and the public.\n\nRULES\n• Use signage to identify hazards.\n• Barricade sanding or spraying areas.\n• Restrict access to work zones.\n• Remove signage only when hazards are cleared.', true),
  ('system', 'SOP-047', 'SOP-047 – Subcontractor Management', E'PURPOSE\nTo ensure subcontractors meet company standards.\n\nREQUIREMENTS\n• Subcontractors must follow all SOPs.\n• Provide proof of insurance and safety compliance.\n• Work must be inspected by foreman.\n\nVIOLATIONS\n• Unsafe conduct may result in removal from site.', true),
  ('system', 'SOP-048', 'SOP-048 – Environmental Protection & Waste Disposal', E'PURPOSE\nTo handle waste responsibly and protect the environment.\n\nRULES\n• Dispose of waste in approved containers only.\n• Never dump liquids down drains or outside.\n• Vacuum dust; do not sweep into air.\n• Bag debris before disposal.', true),
  ('system', 'SOP-049', 'SOP-049 – Security & Theft Prevention', E'PURPOSE\nTo protect company and customer property.\n\nRULES\n• Lock vehicles at all times.\n• Do not leave tools unsecured.\n• Report lost or stolen items immediately.', true),
  ('system', 'SOP-050', 'SOP-050 – After-Hours Site Access', E'PURPOSE\nTo control access outside normal hours.\n\nRULES\n• No after-hours access without approval.\n• No unauthorized persons on job sites.\n• Keys and codes are confidential.', true),
  ('system', 'SOP-051', 'SOP-051 – Technology & Device Use', E'PURPOSE\nTo minimize distractions and protect data.\n\nRULES\n• Personal phone use limited to breaks.\n• No unauthorized photos or videos.\n• Protect passwords and credentials.', true),
  ('system', 'SOP-052', 'SOP-052 – Company Image & Appearance', E'PURPOSE\nTo present a professional image.\n\nSTANDARDS\n• Wear clean company clothing.\n• Maintain basic personal hygiene.\n• No smoking or vaping on site or in vehicles.\n• Behave professionally at all times.', true),
  ('system', 'SOP-053', 'SOP-053 – Alcohol, Drugs & Impairment', E'PURPOSE\nTo ensure a safe, professional workplace.\n\nPOLICY\n• No employee may work while impaired.\n• Zero tolerance for impairment on the job.\n• Cannabis prohibited during work hours.\n\nACTION\n• Foreman may remove employee immediately.\n• Discipline up to termination may apply.', true),
  ('system', 'SOP-054', 'SOP-054 – Harassment & Workplace Conduct', E'PURPOSE\nTo maintain a respectful, safe work environment.\n\nPROHIBITED\n• Harassment (verbal, physical, sexual)\n• Bullying, discrimination, threats\n\nEXPECTATIONS\n• Treat everyone with respect.\n• Professional language at all times.\n\nViolations may result in immediate termination.', true),
  ('system', 'SOP-055', 'SOP-055 – Termination & Exit Process', E'PURPOSE\nTo ensure orderly, professional separation.\n\nEXIT REQUIREMENTS\n• Return all tools, equipment, keys, uniforms.\n• Remove personal belongings.\n• Final pay per Ontario ESA requirements.', true),
  ('system', 'SOP-056', 'SOP-056 – Performance Reviews & Advancement', E'PURPOSE\nTo reward performance and professionalism.\n\nCRITERIA\n• SOP compliance, quality, productivity\n• Attendance, attitude, teamwork\n\nRAISES\n• Not automatic; based on performance.\n\nADVANCEMENT\n• Leadership roles are earned, not assumed.', true),
  ('system', 'SOP-057', 'SOP-057 – Company Values & Culture', E'PURPOSE\nTo define how we operate.\n\nCORE VALUES\n• Professionalism, Accountability, Quality, Safety, Respect\n\nCULTURE\n• We do things the right way, not the easy way.\n• Problems are reported, not hidden.\n• Employees represent the company at all times.', true),
  ('system', 'SOP-058', 'SOP-058 – First Aid & Medical Response', E'PURPOSE\nTo ensure prompt, safe response to injuries.\n\nRULES\n• First aid kits must be available and stocked.\n• Stop work immediately if injury occurs.\n• Do not move injured person unless danger exists.\n• Call 911 for serious injuries.\n• Complete incident report same day.\n\nSafety comes before production.', true),
  ('system', 'SOP-059', 'SOP-059 – First Aid Quick Reference', E'EMERGENCY? CALL 911 IMMEDIATELY\n\nGENERAL RULES\n• Stop work if someone is injured.\n• Stay calm.\n• Do NOT move injured person.\n• Use gloves and PPE.\n• Report ALL injuries.\n\nAFTER ANY INJURY\n• Notify foreman immediately.\n• Complete first aid log.\n• Do NOT hide injuries.', true)
ON CONFLICT DO NOTHING;