-- Seed remaining system SOPs (21-59)
INSERT INTO public.sops (source, system_key, title, content_md, ack_required)
VALUES
  ('system', 'SOP-021', 'SOP-021 – Safety at Heights & Ladder Use', E'PURPOSE\nTo prevent falls and injuries when working at height.\n\nRULES\n• Inspect ladders daily.\n• Use the correct ladder for the task.\n• Never stand on the top step.\n• Maintain three points of contact.\n• Do not overreach.\n\nSETUP\n• Place ladders on stable ground.\n• Use ladder feet or levelers.\n• Secure ladders where required.\n\nPROHIBITED\n• Broken or damaged ladders\n• Standing on buckets or makeshift platforms\n• Carrying heavy items while climbing', true),
  
  ('system', 'SOP-022', 'SOP-022 – Disciplinary Matrix & Enforcement', E'PURPOSE\nTo ensure consistent, fair enforcement of all SOPs.\n\nDISCIPLINE LEVELS\nLevel 1 – Verbal Warning: Minor violations, first-time offenses\nLevel 2 – Written Warning: Repeat violations, safety issues, tool neglect\nLevel 3 – Suspension: Serious violations, damage concealment, time theft\nLevel 4 – Termination: Willful safety violations, dishonesty, repeated insubordination\n\nNOTES\n• Discipline may skip levels depending on severity.\n• All incidents are documented.\n• Ignorance of SOPs is not an excuse.', true),
  
  ('system', 'SOP-023', 'SOP-023 – New Construction Site Etiquette', E'PURPOSE\nTo ensure professional behavior on new construction sites.\n\nRULES\n• We are guests on the builder''s site.\n• Follow site rules and safety requirements.\n• Do not interfere with other trades.\n• Do not touch other trades'' tools or materials.\n\nCONDUCT\n• No loud music or inappropriate language.\n• No wandering outside our scope.\n• Keep work area clean at all times.\n\nViolations may result in removal from site.', true),
  
  ('system', 'SOP-024', 'SOP-024 – Prep Standards by Surface Type', E'PURPOSE\nTo standardize surface preparation for adhesion and quality.\n\nDRYWALL\n• Sand all joints and repairs.\n• Remove dust before priming.\n• Spot-prime all patches.\n\nWOOD (TRIM, DOORS)\n• Sand smooth, fill nail holes, caulk gaps.\n• Spot-prime bare wood.\n\nPREVIOUSLY PAINTED\n• Clean to remove dust/grease.\n• Sand to dull sheen.\n• Repair defects before coating.\n\nMETAL\n• Remove rust, degrease surface.\n• Prime with appropriate metal primer.\n\nNo paint without proper prep.', true),
  
  ('system', 'SOP-025', 'SOP-025 – Paint Handling, Mixing & Storage', E'PURPOSE\nTo ensure paint quality, consistency, and safety.\n\nHANDLING\n• Store paint upright with lids sealed.\n• Label all paint with room, color, sheen, and date.\n• Do not leave paint exposed.\n\nMIXING\n• Stir thoroughly before use.\n• Box paint when required for consistency.\n• Do not thin unless approved.\n\nSTORAGE\n• Store in temperature-controlled areas.\n• Protect from freezing or overheating.\n\nSPILLS\n• Clean immediately.\n• Report large spills.', true),
  
  ('system', 'SOP-026', 'SOP-026 – Incident Investigation & Reporting', E'PURPOSE\nTo ensure incidents are reported, documented, and corrected.\n\nINCIDENTS INCLUDE\n• Injury\n• Property damage\n• Near misses\n• Equipment failure\n• Safety violations\n\nPROCESS\n1. Stop work if unsafe.\n2. Secure area.\n3. Notify foreman immediately.\n4. Complete incident report same day.\n5. Take photos if applicable.\n\nNo retaliation for reporting incidents.\nFailure to report is a serious violation.', true),
  
  ('system', 'SOP-027', 'SOP-027 – Safety Orientation & Jobsite Safety', E'PURPOSE\nTo ensure employees understand safety expectations.\n\nREQUIREMENTS\n• Attend safety orientation.\n• Understand site-specific hazards.\n• Wear required PPE.\n• Follow all safety SOPs.\n\nGENERAL SAFETY\n• Keep walkways clear.\n• Report hazards immediately.\n• Use tools only as trained.\n\nRIGHT TO REFUSE\n• Employees may refuse unsafe work.\n• Report concerns to foreman or management.', true),
  
  ('system', 'SOP-028', 'SOP-028 – Employee Onboarding & Probation', E'PURPOSE\nTo ensure new hires are trained and evaluated before full integration.\n\nONBOARDING REQUIREMENTS\n• Review all SOPs\n• Sign acknowledgments\n• Complete safety orientation\n• Review tool, vehicle, and conduct expectations\n\nPROBATION PERIOD\n• First 30–90 days are probationary\n• Performance, attitude, punctuality evaluated\n• May be extended or terminated at management discretion\n\nFailure to follow SOPs during probation may result in immediate termination.', true),
  
  ('system', 'SOP-029', 'SOP-029 – Foreman Daily Report & Photo Standards', E'PURPOSE\nTo document progress, issues, and quality daily.\n\nDAILY REPORT MUST INCLUDE\n• Job name and date\n• Crew on site\n• Work completed\n• Issues or delays\n• Materials used\n• Safety or damage incidents\n\nPHOTO STANDARDS\n• Start-of-day, mid-day, and end-of-day photos\n• Photos must be clear and labeled\n\nReports must be completed daily before clock-out.', true),
  
  ('system', 'SOP-030', 'SOP-030 – Warranty & Touch-Up Work', E'PURPOSE\nTo manage warranty claims professionally.\n\nRULES\n• Warranty work must be approved by management.\n• No unauthorized touch-ups.\n• Document issue with photos and notes.\n\nPROCESS\n1. Receive warranty request.\n2. Inspect and document.\n3. Management approval.\n4. Schedule and complete repair.\n5. Document repair.\n\nWarranty work is not free unless approved.', true),
  
  ('system', 'SOP-031', 'SOP-031 – Weather & Environmental Conditions', E'PURPOSE\nTo ensure coatings perform correctly under proper conditions.\n\nRULES\n• Follow manufacturer temperature and humidity limits.\n• No exterior painting in rain, snow, or freezing conditions.\n• Monitor weather daily.\n\nINDOOR CONDITIONS\n• Ensure proper ventilation.\n• Control dust and airflow.\n\nForemen may stop work if conditions are unsuitable.', true),
  
  ('system', 'SOP-032', 'SOP-032 – Production Rates & Efficiency', E'PURPOSE\nTo maintain productivity and profitability.\n\nEXPECTATIONS\n• Employees are expected to meet reasonable production rates.\n• Work steadily and efficiently.\n• Excessive downtime is not acceptable.\n\nMONITORING\n• Foremen track progress daily.\n• Repeated inefficiency will be addressed.\n\nQuality is never sacrificed for speed.', true),
  
  ('system', 'SOP-033', 'SOP-033 – Material Ordering & Inventory Control', E'PURPOSE\nTo ensure materials are ordered accurately and waste is minimized.\n\nORDERING\n• Materials ordered only by foremen or management.\n• Orders must match approved specs.\n• No unauthorized substitutions.\n\nINVENTORY\n• Log all materials taken from shop.\n• Update inventory upon return.\n• Label partial containers with job name and date.\n\nWASTE\n• Do not over-order.\n• Return usable materials.\n• Dispose of unusable materials properly.', true),
  
  ('system', 'SOP-034', 'SOP-034 – Shop Operations & Opening/Closing', E'PURPOSE\nTo keep the shop clean, safe, and organized.\n\nOPENING\n• Unlock and disarm alarm.\n• Check cleanliness and safety.\n• Confirm equipment readiness.\n\nCLOSING\n• Clean work areas.\n• Put tools, sundries, and paint away.\n• Empty garbage and recycling.\n• Clean bathroom.\n• Turn off lights and equipment.\n• Lock doors and arm alarm.\n\nThe shop must be left clean every day.', true),
  
  ('system', 'SOP-035', 'SOP-035 – Client Walkthrough & Project Handover', E'PURPOSE\nTo ensure professional handover and reduce callbacks.\n\nPROCESS\n• Foreman schedules walkthrough.\n• Inspect all work before client review.\n• Address concerns professionally.\n• Document any punch-list items.\n\nHANDOVER\n• Complete punch-list.\n• Clean area thoroughly.\n• Obtain sign-off when possible.\n\nNo project is complete without proper handover.', true),
  
  ('system', 'SOP-036', 'SOP-036 – Emergency Response', E'PURPOSE\nTo respond quickly and safely to emergencies.\n\nEMERGENCIES INCLUDE\n• Injury\n• Fire\n• Flood\n• Chemical spill\n• Structural hazard\n\nPROCEDURE\n1. Stop work.\n2. Ensure personal safety.\n3. Call emergency services if required.\n4. Notify foreman immediately.\n5. Secure area.\n6. Complete incident report.\n\nDo not resume work until cleared.', true),
  
  ('system', 'SOP-037', 'SOP-037 – Documentation & File Naming', E'PURPOSE\nTo ensure consistent, traceable documentation.\n\nFILE NAMING\n• Format: JobName_Date_Description\n• Example: Smith_St_2025-03-12_DailyReport\n\nSTORAGE\n• Upload files to designated folders only.\n• No personal devices for company records.\n• Photos must be clear and dated.\n\nRETENTION\n• Do not delete company records.\n• Follow retention policies.', true),
  
  ('system', 'SOP-038', 'SOP-038 – Confined Space Awareness', E'PURPOSE\nTo ensure employees recognize confined spaces and avoid unsafe entry.\n\nDEFINITION\nA confined space is an area that:\n• Is not designed for continuous occupancy\n• Has limited entry/exit\n• May contain hazards\n\nEXAMPLES\n• Crawl spaces, attics with limited access\n• Mechanical rooms, tanks or pits\n\nRULES\n• Do NOT enter confined spaces unless trained and authorized.\n• No sanding, spraying, or coating without approval.\n• If unsure, STOP and contact the foreman.', true),
  
  ('system', 'SOP-039', 'SOP-039 – Hazardous Materials & SDS', E'PURPOSE\nTo ensure safe handling of hazardous materials.\n\nRULES\n• All hazardous products must have an SDS available.\n• Employees must review SDS before use.\n• Follow PPE and ventilation requirements.\n\nHANDLING\n• Store chemicals properly.\n• Do not mix products unless approved.\n• Label all containers clearly.\n\nSPILLS\n• Stop work, contain spill.\n• Notify foreman immediately.', true),
  
  ('system', 'SOP-040', 'SOP-040 – Noise & Hearing Protection', E'PURPOSE\nTo protect hearing from excessive noise exposure.\n\nRULES\n• Hearing protection required when using loud equipment:\n  – Sanders, sprayers, compressors, power tools\n• Use earplugs or earmuffs as required.\n• Replace damaged hearing protection.\n\nPROHIBITED\n• Ignoring hearing protection requirements.\n• Modifying equipment to increase noise.', true)
ON CONFLICT DO NOTHING;