-- Seed system SOPs from existing content
INSERT INTO public.sops (source, system_key, title, content_md, ack_required)
VALUES
  ('system', 'SOP-001', 'SOP-001 – Priming a New Construction House', E'PURPOSE\nTo establish a consistent, efficient, and high-quality process for priming drywall in new construction homes.\n\nNON-NEGOTIABLES\n• We DO NOT brush bare drywall. Ever.\n• Walls are rolled first. No cutting first.\n• All belongings, windows, fixtures, and hardware must be protected.\n• Safety check occurs before work begins.\n\nPROCEDURE\n\n1. Safety & Site Readiness\n• Confirm site is safe and free of hazards.\n• Confirm ventilation if spraying.\n• Protect windows, hinges, countertops, fixtures, floors, and non-painted surfaces.\n\n2. Wall Priming\n• Roll all walls with drywall primer.\n• Do not cut first.\n• Maintain wet edge and even coverage.\n\n3. Ceiling Priming\nOption A – Spray & Back-Roll (Preferred):\n• Spray ceilings evenly.\n• Back-roll with 20 mil roller.\n• Spray all corners and angles normally brushed.\n\nOption B – Roll + Spray Corners:\n• Roll ceilings with 20 mil roller.\n• Spray all vertical and horizontal corners afterward.\n\nFINAL CHECK\n• No missed areas.\n• No overspray.\n• Uniform primer coverage.', true),
  
  ('system', 'SOP-002', 'SOP-002 – Painting Ceilings (New Construction, Primed)', E'PURPOSE\nTo produce a finished ceiling surface using spray and back-roll with minimal coats.\n\nNON-NEGOTIABLES\n• All drywall must be sanded.\n• Spray and back-roll only.\n• 20 mil roller only.\n• Protection is mandatory.\n\nPROCEDURE\n1. Sand ceilings and remove dust.\n2. Protect windows, walls, fixtures, and floors.\n3. Spray ceilings evenly.\n4. Back-roll immediately with 20 mil roller.\n5. Aim for one-coat finish; second coat only if required.', true),
  
  ('system', 'SOP-003', 'SOP-003 – Interior Painting Sequence (New Construction)', E'MANDATORY ORDER\n1. Prime walls and ceilings\n2. Paint ceilings\n3. Paint walls\n4. Paint trim, doors, and frames\n\nRULES\n• No out-of-sequence work.\n• Each stage must be inspected before proceeding.', true),
  
  ('system', 'SOP-004', 'SOP-004 – Painting Walls (Post-Ceiling)', E'NON-NEGOTIABLES\n• Ceilings must be complete.\n• Protection remains in place.\n• No free-styling application methods.\n\nPROCEDURE\n• Inspect walls for damage; patch and spot-prime as needed.\n• Option A: Spray and back-roll (12–15 mil).\n• Option B: Roll only when spraying is not approved.\n• One full coat minimum; second coat if required.', true),
  
  ('system', 'SOP-005', 'SOP-005 – Bathroom & Facility Use Policy', E'GENERAL POLICY\n• Employees are strictly prohibited from using customer bathrooms, sinks, tubs, or drains.\n• No exceptions.\n\nBATHROOM BREAK SCHEDULE\n• Approved break times: 10:00 AM, 12:00 PM, 2:00 PM.\n• Use public or approved facilities only.\n\nPROHIBITED PRACTICES\n• No outdoor urination (bushes, woods, vehicles).\n• No flushing wipes, feminine products, paper towels.\n• Only toilet paper in toilets.\n\nDISCIPLINE\n• First offense: written warning.\n• Repeat offenses: suspension or termination.', true),
  
  ('system', 'SOP-006', 'SOP-006 – Equipment Storage & Vehicle Use', E'POLICY\n• Vehicles are mobile storage units.\n• Only bring tools needed for the task.\n• Do not unload full vehicles into job sites.\n• No tools left on site overnight (except labeled paint and tray liners).\n\nEND OF DAY\n• Tools returned to vehicle or shop.\n• Vehicles locked.', true),
  
  ('system', 'SOP-007', 'SOP-007 – Equipment Sign-Out & Sundries Tracking', E'EQUIPMENT\n• All tools must be signed out.\n• Condition logged out and in.\n• Missing/damaged tools reported immediately.\n\nSUNDRIES\n• All consumables logged when taken from shop.\n• Weekly review and monthly audits.', true),
  
  ('system', 'SOP-008', 'SOP-008 – Driving, Transportation, Travel Time & Vehicle Use (Ontario)', E'LEGAL BASIS\n• Commuting is unpaid.\n• Employer-directed travel is paid.\n• Company vehicles/fuel do not make commuting paid.\n\nCORE RULES\n• Clock in at job site only.\n• Never clock in from home.\n• GPS/geofence enforced.\n\nSHOP EXCEPTIONS\n• Only instructed driver clocks in at shop.\n• Shop-to-job travel is paid.\n\nCARPOOLING\n• Personal choice.\n• Driver not paid.\n• Riders do not work or load vehicles.\n\nPICKUPS\n• Employer-directed pickups are paid.\n• Clock in at first required stop.\n\nEND OF DAY\n• Clock out when work ends.\n• Travel home unpaid.\n\nCOMPANY VEHICLES\n• Personal use is a privilege.\n• No paid commuting.\n• Fuel for personal use is a bonus.\n\nROOMMATES\n• Living together does not create paid travel.\n• Disputes require personal transportation.\n\nFOREMAN RIDE POLICY\n• Foremen are not chauffeurs.\n• No paid extra trips for employee convenience.\n• Shop → Job only when directed.\n\nNO SMOKING OR VAPING\n• No smoking or vaping in company vehicles.\n• Applies at all times.\n• Violations result in loss of privileges and discipline.', true),
  
  ('system', 'SOP-009', 'SOP-009 – Vacuum Use, Dust Control & Safety', E'PURPOSE\nTo establish safe, effective, and professional procedures for the use, maintenance, cleaning, storage, and selection of vacuum systems on job sites and in the shop.\n\nGENERAL POLICY\n• Always use a vacuum with an appropriate filter and a filter bag when vacuuming dry debris, dust, or fine particles.\n• Vacuuming without a filter or bag is prohibited except for specific wet applications.\n\nEQUIPMENT SELECTION\n• Use the correct vacuum for the task.\n• Do not use a standard shop vacuum for fine drywall dust without a HEPA-rated filter.\n\nFILTERS & BAGS\n• A vacuum must always have an intact filter and filter bag installed.\n• Never operate dry vacuum equipment without both.\n\nSAFETY & DUST CONTROL\n• Dust from sanding contains respirable particles.\n• Use HEPA-rated vacuums for fine dust.\n• Attach vacuum directly to tool when possible.\n• Never use compressed air to blow dust.', true),
  
  ('system', 'SOP-010', 'SOP-010 – Orbital & Sheet Sander Use', E'PURPOSE\nTo ensure high-quality finishes, effective dust extraction, long tool life, and safe operation.\n\nNON-NEGOTIABLES\n• Use correct brand of sandpaper with matching sander.\n• Sandpaper holes MUST align with sander pad holes.\n• Sanders MUST be connected to dust collection.\n• Store sanders in their proper bag or box.\n\nPROPER SANDING PRACTICES\n• Keep sandpaper clean.\n• Stop if paper becomes clogged.\n• Do not press hard.\n• Keep sander flat on surface.\n• Lift sander before stopping.', true),
  
  ('system', 'SOP-011', 'SOP-011 – General Tool Maintenance', E'PURPOSE\nTo ensure all tools are clean, safe, functional, and ready for use.\n\nCORE RULES\n• All tools must be cleaned after use.\n• All tools must be inspected before use.\n• All tools must be stored properly.\n• Damaged or unsafe tools must not be used.\n\nDAILY TOOL CLEANING\n• Roller Cages: Clean immediately after use.\n• Roller Covers: Wash until water runs clear.\n• Brushes: Clean daily, shape bristles before drying.\n\nDAILY INSPECTION – BEFORE USE\n• Check power cords for damage.\n• Check for loose plugs.\n• Check for cracked housings.\n• Verify proper switch operation.', true),
  
  ('system', 'SOP-012', 'SOP-012 – Paint Sprayer Use & Maintenance', E'PURPOSE\nTo ensure paint sprayers are used correctly, cleaned thoroughly, and stored safely.\n\nCORE RULES\n• Sprayers must be cleaned after EVERY use.\n• No sprayer is left dirty overnight.\n• Tips, filters, and guns must be cleaned immediately.\n\nPRE-USE INSPECTION\n• Check for leaks and abnormal noises.\n• Inspect hoses for cuts or soft spots.\n• Verify gun and guard function properly.\n\nCLEANING PROCEDURE\n1. Empty remaining material.\n2. Flush system until fluid runs clear.\n3. Clean gun, tip, and filter.\n\nSAFETY\n• High-pressure spray can inject paint into skin.\n• Never point gun at people.\n• Always engage trigger lock when not spraying.', true),
  
  ('system', 'SOP-013', 'SOP-013 – Prep & Surface Protection', E'PURPOSE\nTo protect customer property and work areas from damage, dust, and overspray.\n\nNON-NEGOTIABLES\n• Protection happens BEFORE prep or painting.\n• No spraying or sanding without protection.\n• Assume everything can be damaged unless protected.\n\nPROCEDURE\n1. Floors: Cover all floors with drop sheets or poly.\n2. Walls & Fixtures: Mask windows, hardware, cabinets.\n3. Containment: Use plastic walls when spraying.\n4. Daily Check: Inspect and repair damaged coverings.\n\nFailure to protect is considered negligence.', true),
  
  ('system', 'SOP-014', 'SOP-014 – End-of-Day Jobsite Shutdown', E'PURPOSE\nTo leave every jobsite safe, clean, secure, and professional.\n\nPROCEDURE\n1. Work Area: Stop work with enough time to clean.\n2. Tools & Materials: Tools stored, paint sealed and labeled.\n3. Cleanup: Vacuum work areas, remove debris.\n4. Safety & Security: Lock doors, shut off equipment.\n5. Final Walk: Foreman does final walkthrough.', true),
  
  ('system', 'SOP-015', 'SOP-015 – Foreman Daily Checklist', E'PURPOSE\nTo ensure consistency, productivity, safety, and communication on every job.\n\nDAILY RESPONSIBILITIES\nMorning:\n• Confirm crew attendance.\n• Review scope of work.\n• Confirm materials and tools.\n• Inspect site safety.\n\nDuring the Day:\n• Monitor quality and sequence.\n• Ensure SOP compliance.\n• Address issues immediately.\n\nEnd of Day:\n• Review progress.\n• Complete daily report.\n• Ensure shutdown SOP is followed.\n\nForemen are accountable for SOP enforcement.', true),
  
  ('system', 'SOP-016', 'SOP-016 – Quality Control & Punch-List', E'PURPOSE\nTo deliver consistent, professional finishes and minimize callbacks.\n\nQUALITY STANDARDS\n• Even coverage\n• No runs, sags, or lap marks\n• Clean lines\n• No missed areas\n\nINSPECTION PROCESS\n1. Self-Check: Painters inspect own work.\n2. Foreman Check: Inspect under proper lighting.\n3. Punch-List: Create list, assign responsibility, complete before next phase.\n\nNo job is complete until punch-list is cleared.', true),
  
  ('system', 'SOP-017', 'SOP-017 – Damage Prevention & Property Protection', E'PURPOSE\nTo prevent damage to customer property.\n\nRULES\n• Treat every home as occupied and finished.\n• Never lean tools against walls.\n• Never drag tools across finished surfaces.\n• Never place tools on counters or furniture.\n\nLADDERS & EQUIPMENT\n• Pad ladder contact points.\n• Use drop cloths under ladders.\n\nINCIDENTS\n• Any damage must be reported immediately.\n• Complete incident report same day.\n\nFailure to report damage is a serious violation.', true),
  
  ('system', 'SOP-018', 'SOP-018 – Foreman Authority & Decision-Making', E'PURPOSE\nTo define foreman authority and decision-making power.\n\nAUTHORITY\n• Foreman is the highest authority on site.\n• All crew must follow foreman instructions.\n• Foremen enforce all SOPs without exception.\n\nForemen MAY decide:\n• Daily work sequencing\n• Tool usage\n• Quality corrections\n• Safety stoppages\n\nForemen MAY NOT decide:\n• Price or scope changes\n• Free extras for customers\n• Deviations from SOPs\n\nESCALATION\n• Any scope or cost changes must be escalated.\n• When in doubt: STOP and ASK.', true),
  
  ('system', 'SOP-019', 'SOP-019 – Customer Interaction & Communication', E'PURPOSE\nTo ensure professional, consistent communication with customers.\n\nGENERAL RULES\n• Be polite, professional, and brief.\n• Do not overshare information.\n• Do not promise anything.\n\nEMPLOYEES MAY SAY\n• What work is scheduled today\n• General progress updates\n• That questions will be passed to management\n\nEMPLOYEES MAY NOT SAY\n• Pricing or discounts\n• Schedule guarantees\n• Authorization for extra work\n\nAll change requests go to foreman, then management.', true),
  
  ('system', 'SOP-020', 'SOP-020 – Change Orders', E'PURPOSE\nTo control scope, pricing, and approval of extra work.\n\nRULES\n• No extra work without written change order.\n• Verbal approvals are invalid.\n• \"While you''re here\" work is not allowed.\n\nPROCESS\n1. Customer requests change.\n2. Foreman documents request.\n3. Management prices change.\n4. Customer signs approval.\n5. Work is scheduled and completed.\n\nUnauthorized work will not be paid.', true)
ON CONFLICT DO NOTHING;